# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(PipelineLevelVariable)
    - bash: echo BuildNumber:$(Build.BuildNumber)
    - bash: echo BuildId:$(Build.BuildId)
    - bash: echo SourceBranchName:$(Build.SourceBranchName)
    - bash: echo SourcesDirectory:$(Build.SourcesDirectory)
    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: echo DefaultWorkingDirectory:$(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
  
  # - job: SecondJob
  #   steps:
  #   - bash: echo Build / SecondJob
    

# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     environment: DevDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(environment) / FirstJob


# - stage: QADeploy
#   dependsOn: Build
#   variables:
#     environment: QADeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(environment) / FirstJob


# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   variables:
#     environment: ProdDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo environment / FirstJob